services:
  spellbot:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TOKEN: ${TOKEN}

    depends_on:
      lavalink:
        condition: service_healthy

  lavalink:
    # pin the image version to Lavalink v4
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: on-failure
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    expose:
      - 2333
    ports:
      - "2333:2333"
    environment:
      - SERVER_PORT=2333
      - SERVER_ADDRESS=0.0.0.0
      - LAVALINK_SERVER_PASSWORD=youshallnotpass

    healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
